# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0da2d2cadbe04697854f9f0115d1d1a28ad8a54567993fdd8c616689ef314fa7ca8b1a4a1a0662ee9eb8b707481144b0a87178d20df9987d6223eb1cacbc9e6

test:
  secret_key_base: 5776a0be5840c5981a4158388004808cce975f07101a48f8f1f91409c2346e19005d62a9a525b5a1041e275e25ee19c3f5c1a6bfc62fc1c98e48c9f684d0e035

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
